FROM python:3.8-slim-buster





WORKDIR /flask_app

# WORKDIR /usr/src/app/flask_app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

# CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]

